export const country = [{
  'code': 'AD',
  'zh-TW': '安道爾',
  'en': 'Andorra',
  'zh-CN': '安道尔'
}, {
  'code': 'AE',
  'zh-TW': '阿拉伯聯合大公國',
  'en': 'United Arab Emirates',
  'zh-CN': '阿拉伯联合酋长国'
}, {
  'code': 'AF',
  'zh-TW': '阿富汗',
  'en': 'Afghanistan',
  'zh-CN': '阿富汗'
}, {
  'code': 'AG',
  'zh-TW': '安地卡及巴布達',
  'en': 'Antigua and Barbuda',
  'zh-CN': '安提瓜和巴布达'
}, {
  'code': 'AI',
  'zh-TW': '安圭拉',
  'en': 'Anguilla',
  'zh-CN': '安圭拉'
}, {
  'code': 'AL',
  'zh-TW': '阿爾巴尼亞',
  'en': 'Albania',
  'zh-CN': '阿尔巴尼亚'
}, {
  'code': 'AM',
  'zh-TW': '亞美尼亞',
  'en': 'Armenia',
  'zh-CN': '亚美尼亚'
}, {
  'code': 'AN',
  'zh-TW': '荷屬安替列斯',
  'en': 'Netherlands Antilles',
  'zh-CN': '荷属安的列斯群岛'
}, {
  'code': 'AO',
  'zh-TW': '安哥拉',
  'en': 'Angola',
  'zh-CN': '安哥拉'
}, {
  'code': 'AQ',
  'zh-TW': '南極洲',
  'en': 'Antarctica',
  'zh-CN': '南极洲'
}, {
  'code': 'AR',
  'zh-TW': '阿根廷',
  'en': 'Argentina',
  'zh-CN': '阿根廷'
}, {
  'code': 'AS',
  'zh-TW': '美屬薩摩亞',
  'en': 'American Samoa',
  'zh-CN': '东萨摩亚'
}, {
  'code': 'AT',
  'zh-TW': '奧地利',
  'en': 'Austria',
  'zh-CN': '奥地利'
}, {
  'code': 'AU',
  'zh-TW': '澳大利亞',
  'en': 'Australia',
  'zh-CN': '澳大利亚'
}, {
  'code': 'AW',
  'zh-TW': '阿路巴',
  'en': 'Aruba',
  'zh-CN': '阿鲁巴'
}, {
  'code': 'AX',
  'zh-TW': '奧蘭群島',
  'en': 'Åland Islands',
  'zh-CN': '奥兰群岛'
}, {
  'code': 'AZ',
  'zh-TW': '亞塞拜然',
  'en': 'Azerbaijan',
  'zh-CN': '阿塞拜疆'
}, {
  'code': 'BA',
  'zh-TW': '波士尼亞赫塞哥維納',
  'en': 'Bosnia and Herzegovina',
  'zh-CN': '波斯尼亚和黑山共和国'
}, {
  'code': 'BB',
  'zh-TW': '巴貝多',
  'en': 'Barbados',
  'zh-CN': '巴巴多斯'
}, {
  'code': 'BD',
  'zh-TW': '孟加拉',
  'en': 'Bangladesh',
  'zh-CN': '孟加拉'
}, {
  'code': 'BE',
  'zh-TW': '比利時',
  'en': 'Belgium',
  'zh-CN': '比利时'
}, {
  'code': 'BF',
  'zh-TW': '布吉納法索',
  'en': 'Burkina Faso',
  'zh-CN': '布基纳法索'
}, {
  'code': 'BG',
  'zh-TW': '保加利亞',
  'en': 'Bulgaria',
  'zh-CN': '保加利亚'
}, {
  'code': 'BH',
  'zh-TW': '巴林',
  'en': 'Bahrain',
  'zh-CN': '巴林'
}, {
  'code': 'BI',
  'zh-TW': '浦隆地',
  'en': 'Burundi',
  'zh-CN': '布隆迪'
}, {
  'code': 'BJ',
  'zh-TW': '貝南',
  'en': 'Benin',
  'zh-CN': '贝宁'
}, {
  'code': 'BL',
  'zh-TW': '聖巴瑟米',
  'en': 'Saint Barthélemy',
  'zh-CN': '圣巴泰勒米岛'
}, {
  'code': 'BM',
  'zh-TW': '百慕達',
  'en': 'Bermuda',
  'zh-CN': '百慕大'
}, {
  'code': 'BN',
  'zh-TW': '汶萊',
  'en': 'Brunei',
  'zh-CN': '文莱'
}, {
  'code': 'BO',
  'zh-TW': '玻利維亞',
  'en': 'Bolivia',
  'zh-CN': '玻利维亚'
}, {
  'code': 'BQ',
  'zh-TW': '波納爾島、聖艾斯塔得斯島及薩巴島',
  'en': 'Bonaire, Sint Eustatius and Saba',
  'zh-CN': '博奈尔岛, 圣尤斯特歇斯岛和萨巴岛'
}, {
  'code': 'BR',
  'zh-TW': '巴西',
  'en': 'Brazil',
  'zh-CN': '巴西'
}, {
  'code': 'BS',
  'zh-TW': '巴哈馬',
  'en': 'Bahamas',
  'zh-CN': '巴哈马'
}, {
  'code': 'BT',
  'zh-TW': '不丹',
  'en': 'Bhutan',
  'zh-CN': '不丹'
}, {
  'code': 'BV',
  'zh-TW': '布威島',
  'en': 'Bouvet Island',
  'zh-CN': '布韦岛'
}, {
  'code': 'BW',
  'zh-TW': '波札那',
  'en': 'Botswana',
  'zh-CN': '博茨瓦纳'
}, {
  'code': 'BY',
  'zh-TW': '白俄羅斯',
  'en': 'Belarus',
  'zh-CN': '白俄罗斯'
}, {
  'code': 'BZ',
  'zh-TW': '貝里斯',
  'en': 'Belize',
  'zh-CN': '伯里兹'
}, {
  'code': 'CA',
  'zh-TW': '加拿大',
  'en': 'Canada',
  'zh-CN': '加拿大'
}, {
  'code': 'CC',
  'zh-TW': '可可斯群島',
  'en': 'Cocos Islands',
  'zh-CN': '科库斯群岛'
}, {
  'code': 'CD',
  'zh-TW': '剛果民主共和國',
  'en': 'The Democratic Republic Of Congo',
  'zh-CN': '刚果民主共和国'
}, {
  'code': 'CF',
  'zh-TW': '中非',
  'en': 'Central African Republic',
  'zh-CN': '中非共和国'
}, {
  'code': 'CG',
  'zh-TW': '剛果',
  'en': 'Congo',
  'zh-CN': '刚果'
}, {
  'code': 'CH',
  'zh-TW': '瑞士',
  'en': 'Switzerland',
  'zh-CN': '瑞士'
}, {
  'code': 'CI',
  'zh-TW': '象牙海岸',
  'en': 'Côte d"Ivoire',
  'zh-CN': '象牙海岸'
}, {
  'code': 'CK',
  'zh-TW': '庫克群島',
  'en': 'Cook Islands',
  'zh-CN': '库克群岛'
}, {
  'code': 'CL',
  'zh-TW': '智利',
  'en': 'Chile',
  'zh-CN': '智利'
}, {
  'code': 'CM',
  'zh-TW': '喀麥隆',
  'en': 'Cameroon',
  'zh-CN': '喀麦隆'
}, {
  'code': 'CN',
  'zh-TW': '中國',
  'en': 'China',
  'zh-CN': '中国'
}, {
  'code': 'CO',
  'zh-TW': '哥倫比亞',
  'en': 'Colombia',
  'zh-CN': '哥伦比亚'
}, {
  'code': 'CR',
  'zh-TW': '哥斯大黎加',
  'en': 'Costa Rica',
  'zh-CN': '哥斯达黎加'
}, {
  'code': 'CU',
  'zh-TW': '古巴',
  'en': 'Cuba',
  'zh-CN': '古巴'
}, {
  'code': 'CV',
  'zh-TW': '維德角',
  'en': 'Cape Verde',
  'zh-CN': '佛得角'
}, {
  'code': 'CW',
  'zh-TW': '古拉果',
  'en': 'Curaçao',
  'zh-CN': '库拉索岛'
}, {
  'code': 'CX',
  'zh-TW': '聖誕島',
  'en': 'Christmas Island',
  'zh-CN': '圣诞岛'
}, {
  'code': 'CY',
  'zh-TW': '賽普勒斯',
  'en': 'Cyprus',
  'zh-CN': '塞浦路斯'
}, {
  'code': 'CZ',
  'zh-TW': '捷克共和國',
  'en': 'Czech Republic',
  'zh-CN': '捷克共和国'
}, {
  'code': 'DE',
  'zh-TW': '德國',
  'en': 'Germany',
  'zh-CN': '德国'
}, {
  'code': 'DJ',
  'zh-TW': '吉布地',
  'en': 'Djibouti',
  'zh-CN': '吉布提'
}, {
  'code': 'DK',
  'zh-TW': '丹麥',
  'en': 'Denmark',
  'zh-CN': '丹麦'
}, {
  'code': 'DM',
  'zh-TW': '多米尼克',
  'en': 'Dominica',
  'zh-CN': '多米尼加联邦'
}, {
  'code': 'DO',
  'zh-TW': '多明尼加',
  'en': 'Dominican Republic',
  'zh-CN': '多米尼加共和国'
}, {
  'code': 'DZ',
  'zh-TW': '阿爾及利',
  'en': 'Algeria',
  'zh-CN': '阿尔及利亚'
}, {
  'code': 'EC',
  'zh-TW': '厄瓜多爾',
  'en': 'Ecuador',
  'zh-CN': '厄瓜多尔'
}, {
  'code': 'EE',
  'zh-TW': '愛沙尼亞',
  'en': 'Estonia',
  'zh-CN': '爱沙尼亚'
}, {
  'code': 'EG',
  'zh-TW': '埃及',
  'en': 'Egypt',
  'zh-CN': '埃及'
}, {
  'code': 'EH',
  'zh-TW': '西撒哈拉沙漠',
  'en': 'Western Sahara',
  'zh-CN': '西撒哈拉'
}, {
  'code': 'ER',
  'zh-TW': '厄利垂亞',
  'en': 'Eritrea',
  'zh-CN': '厄里特尼亚'
}, {
  'code': 'ES',
  'zh-TW': '西班牙',
  'en': 'Spain',
  'zh-CN': '西班牙'
}, {
  'code': 'ET',
  'zh-TW': '衣索比亞',
  'en': 'Ethiopia',
  'zh-CN': '埃塞俄比亚'
}, {
  'code': 'FI',
  'zh-TW': '芬蘭',
  'en': 'Finland',
  'zh-CN': '芬兰'
}, {
  'code': 'FJ',
  'zh-TW': '斐濟',
  'en': 'Fiji',
  'zh-CN': '斐济'
}, {
  'code': 'FK',
  'zh-TW': '福克蘭群島',
  'en': 'Falkland Islands',
  'zh-CN': '富克兰群岛'
}, {
  'code': 'FM',
  'zh-TW': '密克羅尼西亞聯邦',
  'en': 'Micronesia',
  'zh-CN': '密克罗尼西亚'
}, {
  'code': 'FO',
  'zh-TW': '法魯群島',
  'en': 'Faroe Islands',
  'zh-CN': '法罗群岛'
}, {
  'code': 'FR',
  'zh-TW': '法國',
  'en': 'France',
  'zh-CN': '法国'
}, {
  'code': 'GA',
  'zh-TW': '加彭',
  'en': 'Gabon',
  'zh-CN': '加蓬'
}, {
  'code': 'GB',
  'zh-TW': '英國',
  'en': 'United Kingdom',
  'zh-CN': '英国'
}, {
  'code': 'GD',
  'zh-TW': '格瑞那達',
  'en': 'Grenada',
  'zh-CN': '格林纳达'
}, {
  'code': 'GE',
  'zh-TW': '喬治亞',
  'en': 'Georgia',
  'zh-CN': '格鲁吉亚'
}, {
  'code': 'GF',
  'zh-TW': '法屬蓋亞納',
  'en': 'French Guiana',
  'zh-CN': '法属圭亚那'
}, {
  'code': 'GG',
  'zh-TW': '根西島',
  'en': 'Guernsey',
  'zh-CN': '格恩西岛'
}, {
  'code': 'GH',
  'zh-TW': '迦納',
  'en': 'Ghana',
  'zh-CN': '加纳'
}, {
  'code': 'GI',
  'zh-TW': '直布羅陀',
  'en': 'Gibraltar',
  'zh-CN': '直布罗陀'
}, {
  'code': 'GL',
  'zh-TW': '格陵蘭',
  'en': 'Greenland',
  'zh-CN': '格陵兰'
}, {
  'code': 'GM',
  'zh-TW': '甘比亞',
  'en': 'Gambia',
  'zh-CN': '冈比亚'
}, {
  'code': 'GN',
  'zh-TW': '幾內亞',
  'en': 'Guinea',
  'zh-CN': '几内亚'
}, {
  'code': 'GP',
  'zh-TW': '格陵蘭',
  'en': 'Guadeloupe',
  'zh-CN': '瓜德罗普岛'
}, {
  'code': 'GQ',
  'zh-TW': '赤道幾內亞',
  'en': 'Equatorial Guinea',
  'zh-CN': '赤道几内亚'
}, {
  'code': 'GR',
  'zh-TW': '希臘',
  'en': 'Greece',
  'zh-CN': '希腊'
}, {
  'code': 'GS',
  'zh-TW': '南喬治亞和南桑威奇群島',
  'en': 'South Georgia And The South Sandwich Islands',
  'zh-CN': '南乔治亚岛和南桑德韦奇岛'
}, {
  'code': 'GT',
  'zh-TW': '瓜地馬拉',
  'en': 'Guatemala',
  'zh-CN': '危地马拉'
}, {
  'code': 'GU',
  'zh-TW': '關島',
  'en': 'Guam',
  'zh-CN': '关岛'
}, {
  'code': 'GW',
  'zh-TW': '比索',
  'en': 'Guinea-Bissau',
  'zh-CN': '几内亚比绍共和国'
}, {
  'code': 'GY',
  'zh-TW': '蓋亞納',
  'en': 'Guyana',
  'zh-CN': '圭亚那'
}, {
  'code': 'HK',
  'zh-TW': '香港',
  'en': 'Hong Kong',
  'zh-CN': '香港'
}, {
  'code': 'HM',
  'zh-TW': '賀得島和麥克唐納群島',
  'en': 'Heard Island And McDonald Islands',
  'zh-CN': '赫德和麦克唐纳群岛'
}, {
  'code': 'HN',
  'zh-TW': '宏都拉斯',
  'en': 'Honduras',
  'zh-CN': '洪都拉斯'
}, {
  'code': 'HR',
  'zh-TW': '克羅埃西亞',
  'en': 'Croatia',
  'zh-CN': '克罗地亚'
}, {
  'code': 'HT',
  'zh-TW': '海地',
  'en': 'Haiti',
  'zh-CN': '海地'
}, {
  'code': 'HU',
  'zh-TW': '匈牙利',
  'en': 'Hungary',
  'zh-CN': '匈牙利'
}, {
  'code': 'ID',
  'zh-TW': '印尼',
  'en': 'Indonesia',
  'zh-CN': '印度尼西亚'
}, {
  'code': 'IE',
  'zh-TW': '愛爾蘭',
  'en': 'Ireland',
  'zh-CN': '爱尔兰'
}, {
  'code': 'IL',
  'zh-TW': '以色列',
  'en': 'Israel',
  'zh-CN': '以色列'
}, {
  'code': 'IM',
  'zh-TW': '曼島',
  'en': 'Isle Of Man',
  'zh-CN': '曼岛'
}, {
  'code': 'IN',
  'zh-TW': '印度',
  'en': 'India',
  'zh-CN': '印度'
}, {
  'code': 'IO',
  'zh-TW': '英屬印度洋地區',
  'en': 'British Indian Ocean Territory',
  'zh-CN': '英属印度洋领地'
}, {
  'code': 'IQ',
  'zh-TW': '伊拉克',
  'en': 'Iraq',
  'zh-CN': '伊拉克'
}, {
  'code': 'IR',
  'zh-TW': '伊朗',
  'en': 'Iran',
  'zh-CN': '伊朗'
}, {
  'code': 'IS',
  'zh-TW': '冰島',
  'en': 'Iceland',
  'zh-CN': '冰岛'
}, {
  'code': 'IT',
  'zh-TW': '義大利',
  'en': 'Italy',
  'zh-CN': '意大利'
}, {
  'code': 'JE',
  'zh-TW': '澤西島',
  'en': 'Jersey',
  'zh-CN': '泽西岛'
}, {
  'code': 'JM',
  'zh-TW': '牙買',
  'en': 'Jamaica',
  'zh-CN': '牙买加'
}, {
  'code': 'JO',
  'zh-TW': '約旦',
  'en': 'Jordan',
  'zh-CN': '约旦'
}, {
  'code': 'JP',
  'zh-TW': '日本',
  'en': 'Japan',
  'zh-CN': '日本'
}, {
  'code': 'KE',
  'zh-TW': '肯亞',
  'en': 'Kenya',
  'zh-CN': '肯尼亚'
}, {
  'code': 'KG',
  'zh-TW': '吉爾吉斯',
  'en': 'Kyrgyzstan',
  'zh-CN': '吉尔吉克斯坦'
}, {
  'code': 'KH',
  'zh-TW': '柬埔寨',
  'en': 'Cambodia',
  'zh-CN': '柬埔寨'
}, {
  'code': 'KI',
  'zh-TW': '吉里巴斯',
  'en': 'Kiribati',
  'zh-CN': '基里巴斯'
}, {
  'code': 'KM',
  'zh-TW': '葛摩',
  'en': 'Comoros',
  'zh-CN': '科摩罗'
}, {
  'code': 'KN',
  'zh-TW': '聖克里斯多福及尼維斯',
  'en': 'Saint Kitts And Nevis',
  'zh-CN': '圣基茨和尼维斯'
}, {
  'code': 'KP',
  'zh-TW': '北韓',
  'en': 'North Korea',
  'zh-CN': '朝鲜'
}, {
  'code': 'KR',
  'zh-TW': '南韓',
  'en': 'South Korea',
  'zh-CN': '韩国'
}, {
  'code': 'KW',
  'zh-TW': '科威特',
  'en': 'Kuwait',
  'zh-CN': '科威特'
}, {
  'code': 'KY',
  'zh-TW': '開曼群島',
  'en': 'Cayman Islands',
  'zh-CN': '开曼群岛'
}, {
  'code': 'KZ',
  'zh-TW': '哈薩克',
  'en': 'Kazakhstan',
  'zh-CN': '哈萨克斯坦'
}, {
  'code': 'LA',
  'zh-TW': '寮國',
  'en': 'Laos',
  'zh-CN': '老挝'
}, {
  'code': 'LB',
  'zh-TW': '黎巴嫩',
  'en': 'Lebanon',
  'zh-CN': '黎巴嫩'
}, {
  'code': 'LC',
  'zh-TW': '聖露西亞',
  'en': 'Saint Lucia',
  'zh-CN': '圣卢西亚'
}, {
  'code': 'LI',
  'zh-TW': '列支敦斯登',
  'en': 'Liechtenstein',
  'zh-CN': '列支敦士登'
}, {
  'code': 'LK',
  'zh-TW': '斯里蘭卡',
  'en': 'Sri Lanka',
  'zh-CN': '斯里兰卡'
}, {
  'code': 'LR',
  'zh-TW': '賴比瑞亞',
  'en': 'Liberia',
  'zh-CN': '利比里亚'
}, {
  'code': 'LS',
  'zh-TW': '賴索托',
  'en': 'Lesotho',
  'zh-CN': '莱索托'
}, {
  'code': 'LT',
  'zh-TW': '立陶宛',
  'en': 'Lithuania',
  'zh-CN': '立陶宛'
}, {
  'code': 'LU',
  'zh-TW': '盧森堡',
  'en': 'Luxembourg',
  'zh-CN': '卢森堡'
}, {
  'code': 'LV',
  'zh-TW': '拉脫維亞',
  'en': 'Latvia',
  'zh-CN': '拉脱维亚'
}, {
  'code': 'LY',
  'zh-TW': '利比亞',
  'en': 'Libya',
  'zh-CN': '利比亚'
}, {
  'code': 'MA',
  'zh-TW': '摩洛哥',
  'en': 'Morocco',
  'zh-CN': '摩洛哥'
}, {
  'code': 'MC',
  'zh-TW': '摩納哥',
  'en': 'Monaco',
  'zh-CN': '摩纳哥'
}, {
  'code': 'MD',
  'zh-TW': '摩爾多瓦',
  'en': 'Moldova',
  'zh-CN': '摩尔多瓦'
}, {
  'code': 'ME',
  'zh-TW': '蒙特尼格羅',
  'en': 'Montenegro',
  'zh-CN': '黑山'
}, {
  'code': 'MF',
  'zh-TW': '聖馬丁',
  'en': 'Saint Martin',
  'zh-CN': '圣马丁'
}, {
  'code': 'MG',
  'zh-TW': '馬達加斯加',
  'en': 'Madagascar',
  'zh-CN': '马达加斯加'
}, {
  'code': 'MH',
  'zh-TW': '馬紹爾群島',
  'en': 'Marshall Islands',
  'zh-CN': '马绍尔群岛'
}, {
  'code': 'MK',
  'zh-TW': '馬其頓',
  'en': 'Macedonia',
  'zh-CN': '马其顿王国'
}, {
  'code': 'ML',
  'zh-TW': '馬利',
  'en': 'Mali',
  'zh-CN': '马里'
}, {
  'code': 'MM',
  'zh-TW': '緬甸',
  'en': 'Myanmar',
  'zh-CN': '缅甸'
}, {
  'code': 'MN',
  'zh-TW': '蒙古',
  'en': 'Mongolia',
  'zh-CN': '蒙古'
}, {
  'code': 'MO',
  'zh-TW': '澳門',
  'en': 'Macao',
  'zh-CN': '澳门特区'
}, {
  'code': 'MP',
  'zh-TW': '馬里亞納群島',
  'en': 'Northern Mariana Islands',
  'zh-CN': '美属北马里亚纳群岛'
}, {
  'code': 'MQ',
  'zh-TW': '法屬玻里尼西亞',
  'en': 'Martinique',
  'zh-CN': '马提尼克岛'
}, {
  'code': 'MR',
  'zh-TW': '茅利塔尼亞',
  'en': 'Mauritania',
  'zh-CN': '毛里塔尼亚'
}, {
  'code': 'MS',
  'zh-TW': '蒙特色拉特島',
  'en': 'Montserrat',
  'zh-CN': '蒙特塞拉群岛'
}, {
  'code': 'MT',
  'zh-TW': '馬爾他',
  'en': 'Malta',
  'zh-CN': '马耳他'
}, {
  'code': 'MU',
  'zh-TW': '模里西斯',
  'en': 'Mauritius',
  'zh-CN': '毛里求斯'
}, {
  'code': 'MV',
  'zh-TW': '馬爾地夫',
  'en': 'Maldives',
  'zh-CN': '马尔代夫'
}, {
  'code': 'MW',
  'zh-TW': '馬拉威',
  'en': 'Malawi',
  'zh-CN': '马拉维'
}, {
  'code': 'MX',
  'zh-TW': '墨西哥',
  'en': 'Mexico',
  'zh-CN': '墨西哥'
}, {
  'code': 'MY',
  'zh-TW': '馬來西亞',
  'en': 'Malaysia',
  'zh-CN': '马来西亚'
}, {
  'code': 'MZ',
  'zh-TW': '莫三比克',
  'en': 'Mozambique',
  'zh-CN': '莫桑比克'
}, {
  'code': 'NA',
  'zh-TW': '納米比亞',
  'en': 'Namibia',
  'zh-CN': '纳米比亚'
}, {
  'code': 'NC',
  'zh-TW': '新喀里多尼亞群島',
  'en': 'New Caledonia',
  'zh-CN': '新克里多尼亚群岛'
}, {
  'code': 'NE',
  'zh-TW': '尼日',
  'en': 'Niger',
  'zh-CN': '尼日尔'
}, {
  'code': 'NF',
  'zh-TW': '諾福克島',
  'en': 'Norfolk Island',
  'zh-CN': '诺福克岛'
}, {
  'code': 'NG',
  'zh-TW': '奈及利亞',
  'en': 'Nigeria',
  'zh-CN': '尼日利亚'
}, {
  'code': 'NI',
  'zh-TW': '尼加拉瓜',
  'en': 'Nicaragua',
  'zh-CN': '尼加拉瓜'
}, {
  'code': 'NL',
  'zh-TW': '荷蘭',
  'en': 'Netherlands',
  'zh-CN': '荷兰'
}, {
  'code': 'NO',
  'zh-TW': '挪威',
  'en': 'Norway',
  'zh-CN': '挪威'
}, {
  'code': 'NP',
  'zh-TW': '尼泊爾',
  'en': 'Nepal',
  'zh-CN': '尼泊尔'
}, {
  'code': 'NR',
  'zh-TW': '諾魯',
  'en': 'Nauru',
  'zh-CN': '瑙鲁'
}, {
  'code': 'NU',
  'zh-TW': '紐威島',
  'en': 'Niue',
  'zh-CN': '纽埃岛'
}, {
  'code': 'NZ',
  'zh-TW': '紐西蘭',
  'en': 'New Zealand',
  'zh-CN': '新西兰'
}, {
  'code': 'OM',
  'zh-TW': '阿曼',
  'en': 'Oman',
  'zh-CN': '阿曼'
}, {
  'code': 'PA',
  'zh-TW': '巴拿馬',
  'en': 'Panama',
  'zh-CN': '巴拿马'
}, {
  'code': 'PE',
  'zh-TW': '祕魯共和國',
  'en': 'Peru',
  'zh-CN': '秘鲁'
}, {
  'code': 'PF',
  'zh-TW': '法屬玻里尼西亞',
  'en': 'French Polynesia',
  'zh-CN': '法属玻利尼西亚'
}, {
  'code': 'PG',
  'zh-TW': '巴布亞紐幾內亞',
  'en': 'Papua New Guinea',
  'zh-CN': '巴布亚新几内亚'
}, {
  'code': 'PH',
  'zh-TW': '菲律賓',
  'en': 'Philippines',
  'zh-CN': '菲律宾'
}, {
  'code': 'PK',
  'zh-TW': '巴基斯坦',
  'en': 'Pakistan',
  'zh-CN': '巴基斯坦'
}, {
  'code': 'PL',
  'zh-TW': '波蘭',
  'en': 'Poland',
  'zh-CN': '波兰'
}, {
  'code': 'PM',
  'zh-TW': '聖皮埃爾和密克隆',
  'en': 'Saint Pierre And Miquelon',
  'zh-CN': '圣皮埃尔和密克隆群岛'
}, {
  'code': 'PN',
  'zh-TW': '皮特康',
  'en': 'Pitcairn',
  'zh-CN': '皮特克恩岛'
}, {
  'code': 'PR',
  'zh-TW': '波多黎各',
  'en': 'Puerto Rico',
  'zh-CN': '波多黎哥'
}, {
  'code': 'PS',
  'zh-TW': '巴勒斯坦',
  'en': 'Palestine',
  'zh-CN': '巴勒斯坦'
}, {
  'code': 'PT',
  'zh-TW': '葡萄牙',
  'en': 'Portugal',
  'zh-CN': '葡萄牙'
}, {
  'code': 'PW',
  'zh-TW': '帛琉',
  'en': 'Palau',
  'zh-CN': '帕劳'
}, {
  'code': 'PY',
  'zh-TW': '巴拉圭',
  'en': 'Paraguay',
  'zh-CN': '巴拉圭'
}, {
  'code': 'QA',
  'zh-TW': '卡達',
  'en': 'Qatar',
  'zh-CN': '卡塔尔'
}, {
  'code': 'RE',
  'zh-TW': '留尼旺島',
  'en': 'Reunion',
  'zh-CN': '留尼汪岛'
}, {
  'code': 'RO',
  'zh-TW': '羅馬尼亞',
  'en': 'Romania',
  'zh-CN': '罗马尼亚'
}, {
  'code': 'RS',
  'zh-TW': '塞爾維亞',
  'en': 'Serbia',
  'zh-CN': '塞尔维亚'
}, {
  'code': 'RU',
  'zh-TW': '俄羅斯聯邦',
  'en': 'Russia',
  'zh-CN': '俄罗斯'
}, {
  'code': 'RW',
  'zh-TW': '盧安達',
  'en': 'Rwanda',
  'zh-CN': '卢旺达'
}, {
  'code': 'SA',
  'zh-TW': '沙烏地阿拉伯',
  'en': 'Saudi Arabia',
  'zh-CN': '沙特阿拉伯'
}, {
  'code': 'SB',
  'zh-TW': '索羅門群島',
  'en': 'Solomon Islands',
  'zh-CN': '所罗门群岛'
}, {
  'code': 'SC',
  'zh-TW': '塞席爾',
  'en': 'Seychelles',
  'zh-CN': '塞舌尔群岛'
}, {
  'code': 'SD',
  'zh-TW': '蘇丹',
  'en': 'Sudan',
  'zh-CN': '苏丹'
}, {
  'code': 'SE',
  'zh-TW': '瑞典',
  'en': 'Sweden',
  'zh-CN': '瑞典'
}, {
  'code': 'SG',
  'zh-TW': '新加坡',
  'en': 'Singapore',
  'zh-CN': '新加坡'
}, {
  'code': 'SH',
  'zh-TW': '聖赫拿勒島',
  'en': 'Saint Helena',
  'zh-CN': '圣赫勒拿岛'
}, {
  'code': 'SI',
  'zh-TW': '斯洛維尼亞',
  'en': 'Slovenia',
  'zh-CN': '斯洛文尼亚'
}, {
  'code': 'SJ',
  'zh-TW': '冷岸和央麥恩島',
  'en': 'Svalbard And Jan Mayen',
  'zh-CN': '斯瓦尔巴特和扬马延岛'
}, {
  'code': 'SK',
  'zh-TW': '斯洛伐克',
  'en': 'Slovakia',
  'zh-CN': '斯洛伐克'
}, {
  'code': 'SL',
  'zh-TW': '獅子山',
  'en': 'Sierra Leone',
  'zh-CN': '塞拉里昂'
}, {
  'code': 'SM',
  'zh-TW': '聖馬力諾',
  'en': 'San Marino',
  'zh-CN': '圣马力诺'
}, {
  'code': 'SN',
  'zh-TW': '塞內加爾',
  'en': 'Senegal',
  'zh-CN': '塞内加尔'
}, {
  'code': 'SO',
  'zh-TW': '索馬利亞',
  'en': 'Somalia',
  'zh-CN': '索马里'
}, {
  'code': 'SR',
  'zh-TW': '蘇利南',
  'en': 'Suriname',
  'zh-CN': '苏里南'
}, {
  'code': 'SS',
  'zh-TW': '南蘇丹',
  'en': 'South Sudan',
  'zh-CN': '南苏丹'
}, {
  'code': 'ST',
  'zh-TW': '聖多美',
  'en': 'Sao Tome And Principe',
  'zh-CN': '圣多美和普林西比'
}, {
  'code': 'SV',
  'zh-TW': '薩爾瓦多',
  'en': 'El Salvador',
  'zh-CN': '萨尔瓦多'
}, {
  'code': 'SX',
  'zh-TW': '聖馬丁 (荷蘭部分)',
  'en': 'Sint Maarten (Dutch part)',
  'zh-CN': '荷属圣马丁岛'
}, {
  'code': 'SY',
  'zh-TW': '敘利亞',
  'en': 'Syria',
  'zh-CN': '叙利亚'
}, {
  'code': 'SZ',
  'zh-TW': '史瓦濟蘭',
  'en': 'Swaziland',
  'zh-CN': '斯威士兰'
}, {
  'code': 'TC',
  'zh-TW': '土克斯和開卡斯群島',
  'en': 'Turks And Caicos Islands',
  'zh-CN': '特克斯群岛和凯科斯群岛'
}, {
  'code': 'TD',
  'zh-TW': '查德',
  'en': 'Chad',
  'zh-CN': '乍得'
}, {
  'code': 'TF',
  'zh-TW': '法國南方領地',
  'en': 'French Southern Territories',
  'zh-CN': '法属南特立尼达'
}, {
  'code': 'TG',
  'zh-TW': '多哥',
  'en': 'Togo',
  'zh-CN': '多哥'
}, {
  'code': 'TH',
  'zh-TW': '泰國',
  'en': 'Thailand',
  'zh-CN': '泰国'
}, {
  'code': 'TJ',
  'zh-TW': '塔吉克',
  'en': 'Tajikistan',
  'zh-CN': '塔吉克斯坦'
}, {
  'code': 'TK',
  'zh-TW': '托克勞群島',
  'en': 'Tokelau',
  'zh-CN': '联合群岛'
}, {
  'code': 'TL',
  'zh-TW': '東帝汶',
  'en': 'Timor-Leste',
  'zh-CN': '东帝汶'
}, {
  'code': 'TM',
  'zh-TW': '土庫曼',
  'en': 'Turkmenistan',
  'zh-CN': '土库曼斯坦'
}, {
  'code': 'TN',
  'zh-TW': '突尼西亞',
  'en': 'Tunisia',
  'zh-CN': '突尼斯'
}, {
  'code': 'TO',
  'zh-TW': '東加',
  'en': 'Tonga',
  'zh-CN': '汤加'
}, {
  'code': 'TR',
  'zh-TW': '土耳其',
  'en': 'Turkey',
  'zh-CN': '土耳其'
}, {
  'code': 'TT',
  'zh-TW': '千里達及托巴哥',
  'en': 'Trinidad and Tobago',
  'zh-CN': '特立尼达和多巴哥'
}, {
  'code': 'TV',
  'zh-TW': '吐瓦魯',
  'en': 'Tuvalu',
  'zh-CN': '图瓦卢'
}, {
  'code': 'TW',
  'zh-TW': '台灣',
  'en': 'Taiwan',
  'zh-CN': '台湾地区'
}, {
  'code': 'TZ',
  'zh-TW': '坦尚尼亞',
  'en': 'Tanzania',
  'zh-CN': '坦桑尼亚'
}, {
  'code': 'UA',
  'zh-TW': '烏克蘭',
  'en': 'Ukraine',
  'zh-CN': '乌克兰'
}, {
  'code': 'UG',
  'zh-TW': '烏干達',
  'en': 'Uganda',
  'zh-CN': '乌干达'
}, {
  'code': 'UM',
  'zh-TW': '美國外島',
  'en': 'United States Minor Outlying Islands',
  'zh-CN': '美属小奥特兰群岛'
}, {
  'code': 'US',
  'zh-TW': '美國',
  'en': 'United States',
  'zh-CN': '美国'
}, {
  'code': 'UY',
  'zh-TW': '烏拉圭',
  'en': 'Uruguay',
  'zh-CN': '乌拉圭'
}, {
  'code': 'UZ',
  'zh-TW': '烏茲別克斯坦',
  'en': 'Uzbekistan',
  'zh-CN': '乌兹别克斯坦'
}, {
  'code': 'VA',
  'zh-TW': '梵帝崗',
  'en': 'Vatican',
  'zh-CN': '梵蒂冈'
}, {
  'code': 'VC',
  'zh-TW': '聖文森及格瑞那丁',
  'en': 'Saint Vincent And The Grenadines',
  'zh-CN': '圣文森特和格林纳丁斯'
}, {
  'code': 'VE',
  'zh-TW': '委內瑞拉',
  'en': 'Venezuela',
  'zh-CN': '委内瑞拉'
}, {
  'code': 'VG',
  'zh-TW': '英屬維爾京群島',
  'en': 'British Virgin Islands',
  'zh-CN': '英属维京群岛'
}, {
  'code': 'VI',
  'zh-TW': '美屬維爾京群島',
  'en': 'U.S. Virgin Islands',
  'zh-CN': '美属维京群岛'
}, {
  'code': 'VN',
  'zh-TW': '越南',
  'en': 'Vietnam',
  'zh-CN': '越南'
}, {
  'code': 'VU',
  'zh-TW': '萬那杜',
  'en': 'Vanuatu',
  'zh-CN': '瓦努阿图'
}, {
  'code': 'WF',
  'zh-TW': '沃利斯和富突納',
  'en': 'Wallis And Futuna',
  'zh-CN': '瓦利斯群岛和富图纳群岛'
}, {
  'code': 'WS',
  'zh-TW': '薩摩亞',
  'en': 'Samoa',
  'zh-CN': '东萨摩亚'
}, {
  'code': 'YE',
  'zh-TW': '葉門',
  'en': 'Yemen',
  'zh-CN': '也门'
}, {
  'code': 'YT',
  'zh-TW': '馬約特島',
  'en': 'Mayotte',
  'zh-CN': '马约特岛'
}, {
  'code': 'ZA',
  'zh-TW': '南非',
  'en': 'South Africa',
  'zh-CN': '南非'
}, {
  'code': 'ZM',
  'zh-TW': '尚比亞',
  'en': 'Zambia',
  'zh-CN': '赞比亚'
}, {
  'code': 'ZW',
  'zh-TW': '辛巴威',
  'en': 'Zimbabwe',
  'zh-CN': '津巴布韦'
}]
